export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const ACCOUNT_INFO = 'ACCOUNT_INFO';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
export const UPDATE_CUSTOMER_DATA = 'UPDATE_CUSTOMER_DATA';
export const UPDATE_CUSTOMER_TOKEN = 'UPDATE_CUSTOMER_TOKEN';
